"""Build a per-distribution README with an install command and the optional post-install block.

Each distribution installs in one command; referenced (bucket 3) skills — default taps, signed, or
source-available doc skills — are listed as a copy-paste ``hermes skills install`` block so the
extras stay optional without bloating the install.
"""

from __future__ import annotations

from configurator.model import PostInstallRef, SetupStep, Template


def _post_install_block(refs: tuple[PostInstallRef, ...]) -> list[str]:
    if not refs:
        return []
    lines = [
        "",
        "## Referenced skills (auto-installed on apply)",
        "",
        "This distribution authors no skills. The skills below are referenced from trusted",
        "registries and listed machine-readably in `skills.install.json`. The apply flow",
        "(`bootstrap.ps1` / `bootstrap.sh`) auto-runs these — with your confirmation and Hermes'",
        "security scan — so applying the persona lands them installed. To install manually (e.g.",
        "after `hermes profile install`), run:",
        "",
        "```bash",
    ]
    for ref in refs:
        if ref.is_tap:
            lines.append(f"hermes skills tap add {ref.id}")
        else:
            lines.append(f"hermes skills install {ref.id}")
    lines.append("```")
    if any(ref.note for ref in refs):
        lines.append("")
        lines.extend(f"- `{ref.id}` — {ref.note}" for ref in refs if ref.note)
    return lines


def _setup_steps_block(steps: tuple[SetupStep, ...]) -> list[str]:
    if not steps:
        return []
    lines = [
        "",
        "## Local tools (auto-set-up on apply)",
        "",
        "Beyond skills, this distribution provisions local tools that install a standalone binary and",
        "wire a Hermes plugin. The apply flow (`bootstrap.ps1` / `bootstrap.sh`) runs the generated",
        "`setup.steps.ps1` / `setup.steps.sh` — with your confirmation, idempotently, tolerating any",
        "failure. Each is free-to-run and keyless unless marked Tier 1.",
        "",
    ]
    for step in steps:
        label = step.label or step.id
        tier_tag = "" if step.tier == 0 else " (Tier 1 — opt-in)"
        note = f" — {step.note}" if step.note else ""
        lines.append(f"- **{label}**{tier_tag}{note}")
    return lines


def build_readme(template: Template) -> str:
    """Render the distribution README markdown for ``template``."""
    dist = template.distribution
    description = dist.get("description")
    title = description if isinstance(description, str) and description else template.name
    lines = [
        f"# {template.name}",
        "",
        str(title),
        "",
        "Generated by the hermes-setup configurator — **do not hand-edit**. Regenerate with",
        f"`python -m configurator compile {template.name}`.",
        "",
        "## Install",
        "",
        "From a clone of the hermes-setup repo, prefer the bundled installer — it wraps",
        "`hermes profile install` and also registers **`/finish-setup`** on every surface (it seeds a",
        "stable `~/.hermes-setup/meta-skills` copy), offers new-isolated-vs-extend, and prints the",
        "per-profile-sessions note:",
        "",
        "```bash",
        f"./install.sh {template.name}          # POSIX;  --yes to skip prompts",
        f".\\install.ps1 {template.name}         # Windows; -Yes to skip prompts",
        "```",
        "",
        "A bare install also works (a standalone dist folder or Hermes Desktop import):",
        "",
        "```bash",
        f"hermes profile install <path-or-git-url> --name {template.name}",
        "```",
        "",
        "…but a bare `hermes profile install` does not seed the `~/.hermes-setup/meta-skills` fallback,",
        "so `/finish-setup` is then guaranteed only when you open the profile with `hermes -p <profile>`",
        "(and may be absent on the default / Desktop surface until you run the installer once).",
        "",
        "Fill in the keys listed in `.env.EXAMPLE` (all provider keys are optional — any one yields",
        "a working agent). Then run `hermes -p <profile> config check`.",
        "",
        "New to Hermes? Do the one-time host setup first — install Hermes and complete the free",
        "`hermes setup --portal` login (the free baseline that powers chat). Then, after installing,",
        "open the profile (`hermes -p <profile>`) and run **`/finish-setup`** to add any optional",
        "provider keys, install the referenced skills, and health-check.",
        "",
        "> **Sessions are per-profile — nothing is wiped by installing this.** Sessions, auth, and",
        "> memory are per-profile in Hermes. Installing this as a new named profile leaves your other",
        "> profiles (and their chat history) untouched; your previous history still lives in its",
        "> original profile. To land in this profile, make it your sticky default with",
        "> `hermes profile use <profile>`, or open it directly with `hermes -p <profile>`.",
    ]
    lines.extend(_post_install_block(template.post_install))
    lines.extend(_setup_steps_block(template.setup_steps))
    return "\n".join(lines).rstrip() + "\n"
