"""Build a per-distribution README with an install command and the optional post-install block.

Each distribution installs in one command; referenced (bucket 3) skills — default taps, signed, or
source-available doc skills — are listed as a copy-paste ``hermes skills install`` block so the
extras stay optional without bloating the install.
"""

from __future__ import annotations

from configurator.model import PostInstallRef, Template


def _post_install_block(refs: tuple[PostInstallRef, ...]) -> list[str]:
    if not refs:
        return []
    lines = [
        "",
        "## Referenced skills (auto-installed on apply)",
        "",
        "This distribution authors no skills. The skills below are referenced from trusted",
        "registries and listed machine-readably in `skills.install.json`. The apply flow",
        "(`bootstrap.ps1` / `bootstrap.sh`) auto-runs these — with your confirmation and Hermes'",
        "security scan — so applying the persona lands them installed. To install manually (e.g.",
        "after `hermes profile install`), run:",
        "",
        "```bash",
    ]
    for ref in refs:
        if ref.is_tap:
            lines.append(f"hermes skills tap add {ref.id}")
        else:
            lines.append(f"hermes skills install {ref.id}")
    lines.append("```")
    if any(ref.note for ref in refs):
        lines.append("")
        lines.extend(f"- `{ref.id}` — {ref.note}" for ref in refs if ref.note)
    return lines


def build_readme(template: Template) -> str:
    """Render the distribution README markdown for ``template``."""
    dist = template.distribution
    description = dist.get("description")
    title = description if isinstance(description, str) and description else template.name
    lines = [
        f"# {template.name}",
        "",
        str(title),
        "",
        "Generated by the hermes-setup configurator — **do not hand-edit**. Regenerate with",
        f"`python -m configurator compile {template.name}`.",
        "",
        "## Install",
        "",
        "```bash",
        f"hermes profile install <path-or-git-url> --name {template.name}",
        "```",
        "",
        "Fill in the keys listed in `.env.EXAMPLE` (all provider keys are optional — any one yields",
        "a working agent). Then run `hermes -p <profile> config check`.",
    ]
    lines.extend(_post_install_block(template.post_install))
    return "\n".join(lines).rstrip() + "\n"
