"""Generate the per-platform ``setup.steps.{sh,ps1}`` scripts the apply flow runs.

``post_install[]`` covers skills the bootstrap installs via ``hermes skills install`` / ``tap add``.
A ``SetupStep`` covers everything else — installing a standalone binary and wiring its Hermes plugin
(the RTK ``rtk init --agent hermes`` case). Rather than have the shell bootstrap parse complex
command strings out of JSON (fragile without ``jq``), the compiler emits two ready-to-run scripts;
``bootstrap.ps1`` / ``bootstrap.sh`` just invoke the matching one, gated by the user's confirmation.

Each generated step is **idempotent** (skips when its check command reports the tool already set up)
and **tolerant** (a failing step never aborts the apply). Pure functions; stdlib only. Everything
emitted is command text + public URLs — no secrets — and is re-scanned by ``emit`` before writing.
"""

from __future__ import annotations

from configurator.model import SetupStep

POSIX_SCRIPT_NAME = "setup.steps.sh"
WINDOWS_SCRIPT_NAME = "setup.steps.ps1"


def _sh_quote(value: str) -> str:
    """Wrap ``value`` in POSIX single quotes, escaping embedded single quotes."""
    return "'" + value.replace("'", "'\\''") + "'"


def _ps_quote(value: str) -> str:
    """Wrap ``value`` in PowerShell single quotes, doubling embedded single quotes."""
    return "'" + value.replace("'", "''") + "'"


_POSIX_HEADER = """\
#!/usr/bin/env sh
# Generated by hermes-setup — local-tool setup steps (setup_steps). Do NOT hand-edit; regenerate
# with `python -m configurator compile`. Each step installs a local tool and wires its Hermes
# plugin. Idempotent: a step whose check command exits 0 is skipped. Failures are tolerated.
set -u

_run_step() {
  label="$1"; check="$2"; run="$3"
  printf '  step: %s\\n' "$label"
  if [ -n "$check" ] && sh -c "$check" >/dev/null 2>&1; then
    printf '    - already set up, skipping\\n'
    return 0
  fi
  if sh -c "$run"; then printf '    + done\\n'; else printf '    ! failed (tolerated)\\n'; fi
  return 0
}
"""

_WINDOWS_HEADER = """\
# Generated by hermes-setup — local-tool setup steps (setup_steps). Do NOT hand-edit; regenerate
# with `python -m configurator compile`. Each step installs a local tool and wires its Hermes
# plugin. Idempotent: a step whose check expression is $true is skipped. Failures are tolerated.
$ErrorActionPreference = 'Continue'

function Invoke-SetupStep {
  param([string]$Label, [string]$Check, [string]$Run)
  Write-Host "  step: $Label"
  if ($Check) {
    $done = $false
    try { $done = [bool](Invoke-Expression $Check) } catch { $done = $false }
    if ($done) { Write-Host '    - already set up, skipping'; return }
  }
  try { Invoke-Expression $Run; Write-Host '    + done' }
  catch { Write-Host "    ! failed (tolerated): $($_.Exception.Message)" }
}
"""


def _label(step: SetupStep) -> str:
    return step.label or step.id


def build_setup_script_posix(steps: tuple[SetupStep, ...]) -> str:
    """Render ``setup.steps.sh`` for the resolved template's steps (in declaration order)."""
    lines = [_POSIX_HEADER]
    for step in steps:
        args = f"{_sh_quote(_label(step))} {_sh_quote(step.posix_check)} {_sh_quote(step.posix_run)}"
        lines.append(f"_run_step {args}")
    return "\n".join(lines).rstrip() + "\n"


def build_setup_script_windows(steps: tuple[SetupStep, ...]) -> str:
    """Render ``setup.steps.ps1`` for the resolved template's steps (in declaration order)."""
    lines = [_WINDOWS_HEADER]
    for step in steps:
        args = f"-Label {_ps_quote(_label(step))} -Check {_ps_quote(step.windows_check)} -Run {_ps_quote(step.windows_run)}"
        lines.append(f"Invoke-SetupStep {args}")
    return "\n".join(lines).rstrip() + "\n"
