#Requires -Version 5.1
<#
.SYNOPSIS
  Launch the hermes-setup BLANK-SLATE Desktop E2E inside Windows Sandbox — host-safe.

.DESCRIPTION
  Generates a .wsb that maps THIS repo READ-ONLY into a disposable Windows Sandbox and auto-runs
  tests/sandbox/provision.ps1 at logon. The Sandbox is a throwaway VM: nothing it does can touch
  your host, and it is wiped when the window closes. Your real Hermes install
  (%LOCALAPPDATA%\hermes — config.yaml, .env, keys, profiles, auth.json) is never read or written.

.PARAMETER Template      Distribution to test (default: general). Must be compiled under dist/.
.PARAMETER GenerateOnly  Write + validate the .wsb but do NOT launch (CI / inspection).

.EXAMPLE
  pwsh -File tests/sandbox/run-sandbox.ps1
.EXAMPLE
  pwsh -File tests/sandbox/run-sandbox.ps1 -Template il-citizen
.EXAMPLE
  pwsh -File tests/sandbox/run-sandbox.ps1 -GenerateOnly
#>
[CmdletBinding()]
param(
  [string]$Template = 'general',
  [switch]$GenerateOnly
)
$ErrorActionPreference = 'Stop'

$RepoRoot    = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$SandboxRepo = 'C:\hermes-setup'                       # where the repo appears inside the sandbox
$Provision   = "$SandboxRepo\tests\sandbox\provision.ps1"

# ---- preflight -------------------------------------------------------------
$distManifest = Join-Path $RepoRoot "dist\$Template\distribution.yaml"
if (-not (Test-Path $distManifest)) {
  throw "dist\$Template not found. Compile it first:  python -m configurator compile $Template"
}
$sandboxExe = Join-Path $env:WINDIR 'System32\WindowsSandbox.exe'
if (-not (Test-Path $sandboxExe)) {
  Write-Warning "Windows Sandbox is not installed/enabled on this machine."
  Write-Warning "Enable it once (Admin PowerShell), then reboot:"
  Write-Warning "  Enable-WindowsOptionalFeature -Online -FeatureName 'Containers-DisposableClientVM' -All"
  if (-not $GenerateOnly) { throw "WindowsSandbox.exe missing — enable the feature and re-run." }
}

# ---- generate the .wsb -----------------------------------------------------
$wsb = @"
<Configuration>
  <!-- Generated by tests/sandbox/run-sandbox.ps1 — host-safe blank-slate Desktop E2E. -->
  <Networking>Default</Networking>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>$RepoRoot</HostFolder>
      <SandboxFolder>$SandboxRepo</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -NoExit -ExecutionPolicy Bypass -File "$Provision" -Template $Template</Command>
  </LogonCommand>
</Configuration>
"@
$wsbPath = Join-Path $env:TEMP "hermes-blank-$Template.wsb"
Set-Content -LiteralPath $wsbPath -Value $wsb -Encoding UTF8
[xml](Get-Content -LiteralPath $wsbPath -Raw) | Out-Null   # fail loudly if not well-formed XML

Write-Host "Generated Sandbox config: $wsbPath"
Write-Host "  maps (read-only): $RepoRoot  ->  $SandboxRepo"
Write-Host "  logon auto-runs:  provision.ps1 -Template $Template"

if ($GenerateOnly) {
  Write-Host "`n(-GenerateOnly) not launching. Double-click the .wsb, or re-run without -GenerateOnly."
  return
}
Write-Host "`nLaunching Windows Sandbox... your host is untouched; close the window to discard everything."
& $sandboxExe $wsbPath
